language: php
php:
  - 7
  - hhvm
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/

matrix:
  fast_finish: true
